config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :authors
  devise_for :users

  root to: "home#index"
  resources :user_records
  resources :users
  resources :genres
  resources :libraries
  resources :books
  resources :authors

  get "pdf_report" => "report_download#export_general_pdf"
  get "libs_csv_report" => "report_download#export_lib_general_csv"
  get "lib_report/:id" => "report_download#export_lib_pdf", as: "lib_report"
  get "user_report/:id" => "report_download#export_user_pdf", as: "user_report"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :user_record
  has_one_attached :image

  def self.add
    (1..10).each { |i|
      q = "INSERT INTO users(name, surname, age, email, created_at, updated_at) VALUES ('name #{i}', 'surname #{i}', '#{i}', 'user#{i}@gmail.com', NOW(), NOW())"
      ActiveRecord::Base.connection.execute(q)
    }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @query = UsersQuery.new(params[:search_full_name], params[:age], params[:sort_name], params[:sort_age])
    @users = @query.results.page(params[:page] || 1).per(5)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.image.attach(params[:user][:image])

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.image.attach(params[:user][:image]) # attach the image
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:name, :surname, :age, :email, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, multipart: true) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= user.surname %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div class="w-50 d-flex my-2">
  <%= form_tag users_path, method: :get do %>
    <div class="input-group">
      <%= text_field_tag :search_full_name, params[:search_full_name], class: "form-control", placeholder: "Full Name" %>
      <%= hidden_field_tag :sort_name, params[:sort_name] || "asc" %>
      <button class="btn btn-outline-secondary" type="submit">&#x1F50D;</button>
    </div>
  <% end %>
  <% if params[:sort_name] == "asc" %>
    <%= link_to "↓", url_for(request.params.merge({sort_name: "desc"})), class: " fs-5 btn btn-success" %>
  <% else %>
    <%= link_to "↑", url_for(request.params.merge({sort_name: "asc"})), class: "fs-5 btn btn-primary" %>
  <% end %>
</div>

<div class="w-50 d-flex my-2">
  <%= form_tag users_path, method: :get do %>
    <div class="input-group">
      <%= text_field_tag :age, params[:age], class: "form-control", placeholder: "Age" %>
      <%= hidden_field_tag :sort_age, params[:sort_age] || "asc" %>
      <button class="btn btn-outline-secondary" type="submit">&#x1F50D;</button>
    </div>
  <% end %>
  <% if params[:sort_age] == "asc" %>
    <%= link_to "↓", url_for(request.params.merge({sort_age: "desc"})), class: "fs-5 btn btn-success" %>
  <% else %>
    <%= link_to "↑", url_for(request.params.merge({sort_age: "asc"})), class: "fs-5 btn btn-primary" %>
  <% end %>
</div>

<table>
  <thead>
  <tr>
    <th class="p-2 border-1 border-white">ID</th>
    <th class="p-2 border-1 border-white">
      Full Name
    </th>
    <th class="p-2 border-1 border-white">Age</th>
    <th class="p-2 border-1 border-white">Email</th>
    <th class="p-2 border-1 border-white">Card Number</th>
    <th class="p-2 border-1 border-white">Card</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td class="p-2 border-1 border-white"><%= user.id %></td>
      <td class="p-2 border-1 border-white"><%= link_to user.name ? user.name + " " + user.surname : "name surname", user %></td>
      <td class="p-2 border-1 border-white"><%= user.age ? user.age : 10 %></td>
      <td class="p-2 border-1 border-white"><%= user.email %></td>
      <td class="p-2 border-1 border-white">
        <% if user.user_record %>
          <%= user.user_record.id %>
        <% end %>
      </td>
      <td class="p-2 border-1 border-white">
        <%= link_to 'Card', user.user_record %>
      </td>
      <td class="p-2"><%= link_to 'Edit User', edit_user_path(user) %></td>
      <td class="p-2"><%= link_to 'Destroy User', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= paginate @users %>

<%= link_to "New user", new_user_path %>

<style>
    table {
        height: 200px;
    }

    .pagination {
        width: 400px;
    }

    .pagination span {
        padding: .4rem;
    }

</style>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= image_tag(@user.image) if @user.image.attached? %>
<%= render @user %>

<div>
  <%= link_to "Download PDF report", user_report_path, class: "btn btn-primary"%>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>