config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :authors
  devise_for :users

  root to: "home#index"
  resources :user_records
  resources :users
  resources :genres
  resources :libraries
  resources :books
  resources :authors

  get "pdf_report" => "report_download#export_general_pdf"
  get "libs_csv_report" => "report_download#export_lib_general_csv"
  get "lib_report/:id" => "report_download#export_lib_pdf", as: "lib_report"
  get "user_report/:id" => "report_download#export_user_pdf", as: "user_report"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :books
  has_many :user_records
  has_one_attached :image

  def self.add
    (1..10).each { |i|
      loc = i % 2 == 0 ? 'Kharkiv' : 'Odessa'
      q = "INSERT INTO libraries(name, location, created_at, updated_at) VALUES ('name #{i}', '#{loc} #{i}', NOW(), NOW())"
      ActiveRecord::Base.connection.execute(q)
    }
  end

  def self.to_csv
    attributes = %w{name location genre_count user_names}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |library|
        @users = User.joins(:user_record).where(reader_cards: {library_id: library.id})
        csv << [library.name, library.books.count, library.books.select(:genre_id).distinct.count, @users.each do |user| user.name end]
      end
    end
  end


  def book_count
    books.count
  end

  def genre_count
    books.select(:genre_id).distinct.count
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy pdf]

  # GET /libraries or /libraries.json
  def index
    @query = LibrariesQuery.new(params[:search_lib_name], params[:sort_lib_name], params[:sort_location], params[:sort_books], params[:sort_genre])
    @libraries = @query.results.page(params[:page] || 1).per(5)
  end

  # GET /libraries/1 or /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(library_params)
    @library.image.attach(params[:library][:image])

    respond_to do |format|
      if @library.save
        format.html { redirect_to library_url(@library), notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        @library.image.attach(params[:library][:image])
        format.html { redirect_to library_url(@library), notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.require(:library).permit(:name, :location, :image)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/_library.html.erb
<div id="<%= dom_id library %>">
  <p>
    <strong>Name:</strong>
    <%= library.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= library.location %>
  </p>

</div>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Show this library", @library %> |
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Libraries</h1>

<%= link_to 'Download general PDF report', pdf_report_path, class: "btn btn-primary me-3"%>
<%= button_to 'download libs csv', 'libs_csv_report.csv', method: 'get', class: "btn btn-primary mt-3"%>

<%#= button_to 'download libs pdf', 'libs_report' , method: 'get', id: 'exportBtn'%>
<%#= button_to 'download users pdf', 'users_report' , method: 'get', id: 'exportBtn'%>
<%#= button_to 'download libs csv', 'libs_csv_report.csv', method: 'get', id: 'exportBtn'%>

<div class="w-50 d-flex my-2">
  <%= form_tag libraries_path, method: :get do %>
    <div class="input-group">
      <%= text_field_tag :search_lib_name, params[:search_lib_name], class: "form-control", placeholder: "Library Name" %>
      <%= hidden_field_tag :sort_lib_name, params[:sort_lib_name] || "asc" %>
      <button class="btn btn-outline-secondary" type="submit">&#x1F50D;</button>
    </div>
  <% end %>
  <% if params[:sort_lib_name] == "asc" %>
    <%= link_to "↓", url_for(request.params.merge({sort_lib_name: "desc"})), class: " fs-5 btn btn-success" %>
  <% else %>
    <%= link_to "↑", url_for(request.params.merge({sort_lib_name: "asc"})), class: "fs-5 btn btn-primary" %>
  <% end %>
</div>


<table>
  <thead>
  <tr>
    <th class="p-2 border-1 border-white">ID</th>
    <th class="p-2 border-1 border-white">Name</th>
    <th class="p-2 border-1 border-white">
      Location
      <% if params[:sort_location] == "asc" %>
        <%= link_to "↓", url_for(request.params.merge({sort_location: "desc"})), class: " fs-5 btn btn-success" %>
      <% else %>
        <%= link_to "↑", url_for(request.params.merge({sort_location: "asc"})), class: "fs-5 btn btn-primary" %>
      <% end %>
    </th>
    <th class="p-2 border-1 border-white">Year</th>
    <th class="p-2 border-1 border-white">
      Books_Count
      <% if params[:sort_books] == "asc" %>
        <%= link_to "↓", url_for(request.params.merge({sort_books: "desc"})), class: " fs-5 btn btn-success" %>
      <% else %>
        <%= link_to "↑", url_for(request.params.merge({sort_books: "asc"})), class: "fs-5 btn btn-primary" %>
      <% end %>
    </th>
    <th class="p-2 border-1 border-white">
      Genre_Count
      <% if params[:sort_genre] == "asc" %>
        <%= link_to "↓", url_for(request.params.merge({sort_genre: "desc"})), class: " fs-5 btn btn-success" %>
      <% else %>
        <%= link_to "↑", url_for(request.params.merge({sort_genre: "asc"})), class: "fs-5 btn btn-primary" %>
      <% end %>
    </th>
    <th class="p-2 border-1 border-white">street</th>
    <th class="p-2 border-1 border-white">address</th>
    <th class="p-2 border-1 border-white">zipcode</th>
  </tr>
  </thead>
  <tbody>
  <% @libraries.each do |library| %>
    <tr>
      <td class="p-2 border-1 border-white"><%= library.id %></td>
      <td class="p-2 border-1 border-white"><%= library.name %></td>
      <td class="p-2 border-1 border-white"><%= library.location %></td>
      <td class="p-2 border-1 border-white"><%= library.year ? library.year : 2023 %></td>
      <td class="p-2 border-1 border-white"><%= library.books.count %></td>
      <td class="p-2 border-1 border-white"><%= library.books.select(:genre_id).distinct.count  %></td>
      <td class="p-2 border-1 border-white"><%= library.street ? library.street : "no street" %></td>
      <td class="p-2 border-1 border-white"><%= library.address ? library.address : "no address" %></td>
      <td class="p-2 border-1 border-white"><%= library.zipcode ? library.zipcode : "no zipcode" %></td>
      <td class="p-2 "><%= link_to 'Show', library %></td>
      <td class="p-2"><%= link_to 'Edit', edit_library_path(library) %></td>
      <td class="p-2"><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @libraries %>

<%= link_to 'New Library', new_library_path %>

<style>
    table {
        height: 200px;
    }

    .pagination {
        width: 400px;
    }

    .pagination span {
        padding: .4rem;
    }

</style>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= image_tag(@library.image) if @library.image.attached? %>
<%= render @library %>

<div>
  <%= link_to "Download PDF report", lib_report_path, class: "btn btn-primary" %>
  <%= link_to "Edit this library", edit_library_path(@library) %> |
  <%= link_to "Back to libraries", libraries_path %>

  <%= button_to "Destroy this library", @library, method: :delete %>
</div>