config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :authors
  devise_for :users

  root to: "home#index"
  resources :user_records
  resources :users
  resources :genres
  resources :libraries
  resources :books
  resources :authors

  get "pdf_report" => "report_download#export_general_pdf"
  get "libs_csv_report" => "report_download#export_lib_general_csv"
  get "lib_report/:id" => "report_download#export_lib_pdf", as: "lib_report"
  get "user_report/:id" => "report_download#export_user_pdf", as: "user_report"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_record.rb
class UserRecord < ApplicationRecord
  belongs_to :library
  belongs_to :user

  def self.add
    (1..10).each { |i|
      input = UserRecord.new(
        library_id: Library.find(i).id,
        user_id: User.find(i).id,
        created_at: Time.now,
        updated_at: Time.now
      )
      input.save
    }
  end

end

app/controllers/user_records_controller.rb
class UserRecordsController < ApplicationController
  before_action :set_user_record, only: %i[ show edit update destroy ]

  # GET /user_records or /user_records.json
  def index
    @user_records = UserRecord.page(params[:page] || 1).per(5)

    respond_to do |format|
      format.html # Render the default HTML template
      format.json { render json: @user_records } # Render JSON data for API requests
    end
  end
  # GET /user_records/1 or /user_records/1.json
  def show
  end

  # GET /user_records/new
  def new
    @user_record = UserRecord.new
  end

  # GET /user_records/1/edit
  def edit
  end

  # POST /user_records or /user_records.json
  def create
    @user_record = UserRecord.new(user_record_params)

    respond_to do |format|
      if @user_record.save
        format.html { redirect_to user_record_url(@user_record), notice: "User record was successfully created." }
        format.json { render :show, status: :created, location: @user_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_records/1 or /user_records/1.json
  def update
    respond_to do |format|
      if @user_record.update(user_record_params)
        format.html { redirect_to user_record_url(@user_record), notice: "User record was successfully updated." }
        format.json { render :show, status: :ok, location: @user_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_records/1 or /user_records/1.json
  def destroy
    @user_record.destroy

    respond_to do |format|
      format.html { redirect_to user_records_url, notice: "User record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_record
      @user_record = UserRecord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_record_params
      params.require(:user_record).permit(:library_id, :user_id)
    end
end

app/helpers/user_records_helper.rb
module UserRecordsHelper
end

app/views/user_records/_form.html.erb
<%= form_with(model: user_record) do |form| %>
  <% if user_record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_record.errors.count, "error") %> prohibited this user_record from being saved:</h2>

      <ul>
        <% user_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :library_id, style: "display: block" %>
    <%= form.text_field :library_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_records/_user_record.html.erb
<div id="<%= dom_id user_record %>">
  <p>
    <strong>ID:</strong>
    <%= user_record.id %>
  </p>

  <p>
    <strong>Library:</strong>
    <%= user_record.library_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_record.user_id %>
  </p>

</div>

app/views/user_records/edit.html.erb
<h1>Editing user record</h1>

<%= render "form", user_record: @user_record %>

<br>

<div>
  <%= link_to "Show this user record", @user_record %> |
  <%= link_to "Back to user records", user_records_path %>
</div>

app/views/user_records/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User records</h1>

<table>
  <thead>
  <tr>
    <th>ID</th>
    <th>Lib_ID</th>
    <th>User_ID</th>
  </tr>
  </thead>
  <tbody>
  <% @user_records.each do |user_record| %>
    <tr>
      <td class="p-2"><%= user_record.id %></td>
      <td class="p-2"><%= user_record.library_id %></td>
      <td class="p-2"><%= user_record.user_id %></td>
      <td class="p-2"><%= link_to 'Show', user_record %></td>
      <td class="p-2"><%= link_to 'Edit', edit_user_record_path(user_record) %></td>
      <td class="p-2"><%= link_to 'Destroy', user_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<%= paginate @user_records %>

<%= link_to "New user record", new_user_record_path %>

<style>
    table {
        height: 200px;
    }

    .pagination {
        width: 400px;
    }

    .pagination span {
        padding: .4rem;
    }

</style>

app/views/user_records/new.html.erb
<h1>New user record</h1>

<%= render "form", user_record: @user_record %>

<br>

<div>
  <%= link_to "Back to user records", user_records_path %>
</div>

app/views/user_records/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_record %>

<div>
  <%= link_to "Edit this user record", edit_user_record_path(@user_record) %> |
  <%= link_to "Back to user records", user_records_path %>

  <%= button_to "Destroy this user record", @user_record, method: :delete %>
</div>